Vertexvis/vertex-dev-dashboard

- src/components/file/FileTable.tsx
- src/components/part/CreatePartDialog.tsx
- src/components/part/PartRow.tsx
- src/components/part/PartTable.tsx
- src/components/part/QueuedTranslationsTable.tsx
- src/components/scene/SceneTable.tsx
- src/lib/api.ts
- src/lib/dates.ts
- src/lib/queued-jobs.ts
- src/pages/api/parts.ts
- src/pages/api/queued-translations.ts
- yarn.lock
Add part creation from recent files; add running & error translation sections to parts page
> Add part creation from recent files; add running & error translation sections to parts page

- src/components/file/FileTable.tsx
- src/components/part/PartTable.tsx
- src/components/part/QueuedTranslationsTable.tsx
- src/components/scene/SceneTable.tsx
- src/components/shared/SkeletonBody.tsx
Adds a common skeleton rendering component & uses it in the places where tables are populate async.
> Add common skeleton rendering component

- src/components/viewer/ViewerSpeedDial.tsx
Add button that copies view camera
> Add button that copies view camera

- src/components/scene/SceneTable.tsx
- src/components/viewer/ViewerSpeedDial.tsx
- src/pages/api/scenes.ts
Add filtering by supplied id to scenes
> Add filtering by supplied id to scenes

- src/components/part/CreatePartDialog.tsx
- src/pages/api/parts.ts
Add checkbox for indexing metadata
> Add checkbox for indexing metadata

- src/components/file/CreateFileDialog.tsx
- src/components/part/CreatePartDialog.tsx
- src/components/part/PartTable.tsx
Add option to redirecto to create a part after file upload
> Add option to redirecto to create a part after file upload

- src/components/viewer/LeftDrawer.tsx
- src/components/viewer/SceneTree.tsx
- src/pages/scene-viewer.tsx
Expand to the selected viewer item in the scene tree
> Expand to the selected viewer item in the scene tree

- src/components/viewer/LeftDrawer.tsx
- src/components/viewer/SceneTree.tsx
> Expand & collapse all

- src/components/part/CreateSceneDialog.tsx
- src/components/part/PartRow.tsx
- src/components/part/PartTable.tsx
- src/pages/api/scenes.ts
Basic create scene from revision w/no error handling
> Basic create scene from revision w/no error handling

- src/components/part/PartTable.tsx
- src/components/scene/SceneTable.tsx
- src/components/shared/CreateSceneDialog.tsx
- src/components/shared/TableToolbar.tsx
- src/pages/api/merged-scenes.ts
Add ability to merge scenes into a new scene
> Add ability to merge scenes into a new scene

- src/components/shared/CreateSceneDialog.tsx
- src/pages/api/scene-view-states.ts
- src/pages/scene-viewer/[sceneId].tsx
- yarn.lock
> Update node client

- next-env.d.ts
- package.json
- src/components/part/PartRow.tsx
- src/lib/metadata.ts
- src/lib/multer/api-storage-engine.ts
- src/lib/vertex-api.ts
- src/pages/api/files.ts
- src/pages/api/part-revisions.ts
- src/pages/api/parts.ts
- src/pages/api/queued-translations.ts
- src/pages/api/scene-view-states.ts
- src/pages/api/scenes.ts
- yarn.lock
Change @vertex/viewer-react to 0.10.2
> [API-2198] Change @vertex/viewer-react to 0.10.2

- package.json
- src/components/file/CreateFileDialog.tsx
- src/components/file/FileTable.tsx
- src/components/part/CreatePartDialog.tsx
- src/components/part/PartRow.tsx
- src/components/part/PartTable.tsx
- src/components/part/QueuedTranslationsTable.tsx
- src/components/scene/SceneDrawer.tsx
- src/components/scene/SceneTable.tsx
- src/components/shared/Header.tsx
- src/components/shared/Input.tsx
- src/components/shared/LeftDrawer.tsx
- src/components/shared/TableToolbar.tsx
- src/components/viewer/LeftDrawer.tsx
- src/components/viewer/RightDrawer.tsx
- src/components/viewer/Viewer.tsx
- src/lib/api.ts
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/api/part-revisions.ts
- src/pages/api/parts.ts
- src/pages/api/queued-translations.ts
- src/pages/api/scene-view-states.ts
- src/pages/api/scenes.ts
- src/pages/api/stream-keys.ts
- src/pages/login.tsx
- src/pages/scene-viewer/[sceneId].tsx
- yarn.lock
> [API-2258]: Update deps, add platprod

- src/components/viewer/SceneTree.tsx
> Hide overflow of scene-tree

- src/components/viewer/LeftDrawer.tsx
- src/components/viewer/SceneTree.tsx
- src/lib/metadata.ts
- src/pages/api/scene-items/[id].ts
- src/pages/scene-viewer/[sceneId].tsx
Show metadata when selecting an item in the scene-tree
> Show metadata when selecting an item in the scene-tree

- src/components/viewer/SceneViewStateList.tsx
Add scene-view-state ids to list
> [PLAT-439] Add scene-view-state ids to list

- src/components/part/PartTable.tsx
- src/components/part/QueuedTranslationsTable.tsx
- src/components/viewer/LeftDrawer.tsx
- src/components/viewer/SceneTree.tsx
- src/pages/api/queued-translations.ts
- src/pages/api/scene-items/[id].ts
- yarn.lock
> Adding successful translations

- src/pages/api/merged-scenes.ts
Setting the root scene item to the name of the merged model as the root node.
> [PLAT-697] Merge scenes with root scene item

- src/pages/api/merged-scenes.ts
Commit a scene after merge scene operation
> [PLAT-2071] Commit merge model scene

- src/pages/scene-viewer/[sceneId].tsx
> enable feature lines

- src/components/scene/SceneDrawer.tsx
- src/components/scene/SceneTable.tsx
- src/pages/api/scenes.ts
- src/pages/index.tsx
- Deletion of key/value pairs only occurs when explicitly setting the value to null
- All other keys are edited or inserted into the existing metadata.
https://github.com/Vertexvis/vertex-dev-dashboard/assets/49169871/d1730070-2937-42ea-a722-0c5b4f278aa2
> Adding support for Upsert/Deleting metadata

- src/pages/login.tsx
> update handle reset

- src/components/viewer/Viewer.tsx
- src/pages/scene-viewer/[sceneId].tsx
No longer including metadata on hit requests, due to latency concerns.
> [PLAT-4855] No longer include metadata on a hit

- Dockerfile
- package.json
- yarn.lock
fix vulnerabilities
[TICKET](https://vertexvis.atlassian.net/browse/PLAT-5428)
> PLAT-5428 

- package.json
- yarn.lock
fix vulnerabilities
[TICKET](https://vertexvis.atlassian.net/browse/PLAT-5428)
> PLAT-5428 fix vulnerabilities
